<a href="https://colab.research.google.com/github/jnsbrdbr/andrew-ng/blob/master/L_Rmultivariable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install TensorFlow
# !pip install -q tensorflow-gpu==2.0.0-beta1

try:
  %tensorflow_version 2.x  # Colab only.
except Exception:
  pass

import tensorflow as tf
print(tf.__version__)

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # Colab only.`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.
2.6.0


In [ ]:
import os

# Scientific and vector computation for python
import numpy as np
import pandas as pd
import io
import seaborn as sns

# Plotting library
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D  # needed to plot 3-D surfaces
import matplotlib.pyplot as plt

In [ ]:
!wget https://raw.githubusercontent.com/susilvaalmeida/machine-learning-andrew-ng/master/data/ex1data2.txt


data= pd.read_csv('ex1data2.txt',header=None ).values

--2021-11-09 15:12:01--  https://raw.githubusercontent.com/susilvaalmeida/machine-learning-andrew-ng/master/data/ex1data2.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 657 [text/plain]
Saving to: ‘ex1data2.txt’

ex1data2.txt        100%[===================>]     657  --.-KB/s    in 0s      

2021-11-09 15:12:02 (25.8 MB/s) - ‘ex1data2.txt’ saved [657/657]



In [ ]:
x = data[:, :2]
y = data[:, 2].reshape(-1, 1)
m=len(y)

In [ ]:
print(x)

[[2104    3]
 [1600    3]
 [2400    3]
 [1416    2]
 [3000    4]
 [1985    4]
 [1534    3]
 [1427    3]
 [1380    3]
 [1494    3]
 [1940    4]
 [2000    3]
 [1890    3]
 [4478    5]
 [1268    3]
 [2300    4]
 [1320    2]
 [1236    3]
 [2609    4]
 [3031    4]
 [1767    3]
 [1888    2]
 [1604    3]
 [1962    4]
 [3890    3]
 [1100    3]
 [1458    3]
 [2526    3]
 [2200    3]
 [2637    3]
 [1839    2]
 [1000    1]
 [2040    4]
 [3137    3]
 [1811    4]
 [1437    3]
 [1239    3]
 [2132    4]
 [4215    4]
 [2162    4]
 [1664    2]
 [2238    3]
 [2567    4]
 [1200    3]
 [ 852    2]
 [1852    4]
 [1203    3]]


In [ ]:
print(y)

[[399900]
 [329900]
 [369000]
 [232000]
 [539900]
 [299900]
 [314900]
 [198999]
 [212000]
 [242500]
 [239999]
 [347000]
 [329999]
 [699900]
 [259900]
 [449900]
 [299900]
 [199900]
 [499998]
 [599000]
 [252900]
 [255000]
 [242900]
 [259900]
 [573900]
 [249900]
 [464500]
 [469000]
 [475000]
 [299900]
 [349900]
 [169900]
 [314900]
 [579900]
 [285900]
 [249900]
 [229900]
 [345000]
 [549000]
 [287000]
 [368500]
 [329900]
 [314000]
 [299000]
 [179900]
 [299900]
 [239500]]


In [ ]:
data.shape

(47, 3)

In [ ]:
#data.columns = ['house_size', 'bedrooms', 'house_price']
#data.describe().T

In [ ]:
#def feature_normalize(X, mean=np.zeros(1), std=np.zeros(1)):
#    X = np.array(X)
#    if len(mean.shape) == 1 or len(std.shape) == 1:
#        mean = np.mean(X, axis=0)
#        std = np.std(X, axis=0, ddof=1)

#    X = (X - mean)/std
#    return X, mean, std

In [ ]:
#X_norm, mu, sigma = feature_normalize(data[['house_size', 'bedrooms']])

In [ ]:
#data['house_size_normalized'] = X_norm[:,0]
#data['bedrooms_normalized'] = X_norm[:,1]
#data[['house_size_normalized', 'bedrooms_normalized']].describe().T

In [ ]:
def normalize(x):
  x_norm = x.copy()
  mu = np.zeros(data.shape[1])
  sigma = np.zeros(data.shape[1])
  mu = np.mean(x, axis = 0)
  sigma = np.std(x, axis = 0)
  x_norm = (x - mu) / sigma
  return x_norm, mu, sigma

In [ ]:
x_norm, mu, sigma = normalize(x)

print('Computed mean:', mu)
print('Computed standard deviation:', sigma)

Computed mean: [2000.68085106    3.17021277]
Computed standard deviation: [7.86202619e+02 7.52842809e-01]


In [ ]:
X = np.concatenate([np.ones((m, 1)), x_norm], axis=1)
theta = np.zeros((3))
print(theta)
num_iters=50
alpha=0.03

[0. 0. 0.]


In [ ]:
def computeCostMulti(X, y, theta):
  m = y.shape[0]
  h=np.dot(X,theta)
  J = (1/(2 * m)) * np.sum(np.square(h - y))
  return J

In [ ]:
J=computeCostMulti(X, y, theta)
print("the cost for theta[0,0] is:",J)

the cost for theta[0,0] is: 3082802761003.5


In [ ]:
def gradientDescentMulti(X, y, theta, alpha, num_iters):
  m = y.shape[0]
  J_history = np.zeros(num_iters)
  theta_0 = theta.copy()
  for i in range(0, num_iters):
      h = X.dot(theta_0)
      diff_hy = h - y

      delta = (1/m) * (diff_hy.T.dot(X))
      theta_0 = theta_0 - (alpha * delta.T)
      J_history[i] = computeCostMulti(X, y, theta_0)

  return theta_0, J_history

In [ ]:
theta, _ = gradientDescentMulti(X, y, theta, alpha, num_iters)
print('Theta found by gradient descent:\n', theta)

ValueError: ignored