<a href="https://colab.research.google.com/github/jnsbrdbr/andrew-ng/blob/master/part2/smote%26pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import jaccard_score
from scipy.spatial.distance import pdist, squareform

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd
store = pd.HDFStore('/content/drive/MyDrive/1000/Tdata.h5')

adj=store['adj']
store.close()

In [4]:
store = pd.HDFStore('/content/drive/MyDrive/1000/TCFdf.h5')
CF=store['CFdf']
store.close()

In [5]:
store = pd.HDFStore('/content/drive/MyDrive/1000/TTFdf.h5')
TF=store['TFdf']
store.close()

In [6]:
with pd.HDFStore('/content/drive/MyDrive/1000/TjaccardsimilaritydfR.h5',  mode='r') as newstore:
    jaccardsimilarity = newstore.select('jaccardsimilaritydfR')

In [7]:
store = pd.HDFStore('/content/drive/MyDrive/1000/TcosinesimilaritydfR.h5')
cosine=store['cosine_similaritydfR']

In [8]:
store = pd.HDFStore('/content/drive/MyDrive/1000/TL1normdf.h5')
L1_normdf=store['L1_normdf']
store.close()

In [9]:
store = pd.HDFStore('/content/drive/MyDrive/1000/Tsum.h5')
wsumdf=store['wsumdf']
store.close()

In [10]:
with pd.HDFStore('/content/drive/MyDrive/1000/Tmul.h5',  mode='r') as newstore:
    wmuldf = newstore.select('wmuldf')

In [11]:
store = pd.HDFStore('/content/drive/MyDrive/1000/TLdata.h5')
adjl=store['adjl']
store.close()

# SMOTE:Synthetic Minority Oversampling **TEchnique**

In [14]:
#CF
from imblearn.over_sampling import SMOTE


oversample1 = SMOTE()#k_neighbors=2
CF_smote,CF_label= oversample1.fit_resample(CF,adjl['label'])

In [60]:
#TF
oversample2 = SMOTE()#k_neighbors=2
TF_smote,TF_label= oversample2.fit_resample(TF,adjl['label'])

In [19]:
#jaccardsimilarity
oversample3 = SMOTE()#k_neighbors=2
jaccard_similarity_smote,jaccard_similarity_label= oversample3.fit_resample(jaccardsimilarity,
                                                                            adjl['label'])

In [20]:
oversample4 = SMOTE()#k_neighbors=2
cosine_similarity_smote,cosine_similarity_label= oversample4.fit_resample(cosine,
                                                                          adjl['label'])

In [21]:
#L1_norm
oversample5 = SMOTE()#k_neighbors=2
L1_norm_smote,L1_norm_label= oversample5.fit_resample(L1_normdf,adjl['label'])

In [22]:
#wsum
oversample6 = SMOTE()#k_neighbors=2
wsum_smote,wsum_label= oversample6.fit_resample(wsumdf,adjl['label'])

In [23]:
#wmul
oversample7 = SMOTE()#k_neighbors=2
wmul_smote,wmul_label= oversample7.fit_resample(wmuldf,adjl['label'])

# **PCA**

In [67]:
from sklearn.decomposition import PCA


pca = PCA(n_components=10)
CF_pca = pca.fit_transform(CF_smote)
print(np.round(CF_pca))

[[-1. -3. -0. ... -0. -0. -0.]
 [-1. -3. -0. ... -0. -0. -0.]
 [-1. -3. -0. ... -0. -0. -0.]
 ...
 [-1. -3. -0. ... -0. -0. -0.]
 [-1. -3. -0. ... -0. -0. -0.]
 [-1. -3. -0. ... -0. -0. -0.]]


In [68]:
pca = PCA(n_components=10)
TF_pca = pca.fit_transform(TF_smote)
print(np.round(TF_pca))

[[-169.    0.   -0. ...   -0.    0.   -0.]
 [-169.    0.   -0. ...   -0.   -0.   -0.]
 [-169.    0.   -0. ...   -0.    0.   -0.]
 ...
 [-177.    0.    0. ...    0.   -0.    0.]
 [-173.    0.    0. ...   -0.   -0.   -0.]
 [-173.    0.    0. ...   -0.    0.   -6.]]


In [62]:
pca = PCA(n_components=10)
jaccard_similarity_pca = pca.fit_transform(jaccard_similarity_smote)
print(np.round(jaccard_similarity_pca))

[[-1. -4. -1. ...  3. -0.  0.]
 [-1. -4. -1. ...  3. -0.  0.]
 [-1. -4. -1. ...  3. -0.  0.]
 ...
 [-9.  7. -0. ... -0.  1. -0.]
 [-7.  4. -0. ...  1. -0.  1.]
 [-5.  0. -3. ... -0.  0. -0.]]


In [61]:
pca = PCA(n_components=10)
cosine_similarity_pca = pca.fit_transform(cosine_similarity_smote)
print(np.round(cosine_similarity_pca))

[[-1. -4. -0. ...  3. -0.  0.]
 [-1. -4. -0. ...  3. -0.  0.]
 [-1. -4. -0. ...  3. -0.  0.]
 ...
 [12.  4. -0. ... -0.  0. -0.]
 [-1. -6. -4. ... -0.  0. -0.]
 [-1. -4. -0. ... -1. -0.  0.]]


In [64]:
pca = PCA(n_components=10)
L1_normdf_similarity_pca = pca.fit_transform(L1_norm_smote)
print(np.round(L1_normdf_similarity_pca))

[[-1. -4. -0. ...  3. -0.  0.]
 [-1. -4. -0. ...  3. -0.  0.]
 [-1. -4. -0. ...  3. -0.  0.]
 ...
 [-0. -4. -0. ...  3. -0.  0.]
 [ 2. -2. -0. ... -1. -0.  0.]
 [-4. -0. -0. ... -1. -0.  0.]]


In [65]:
pca = PCA(n_components=10)
wsumdf_similarity_pca = pca.fit_transform(wsum_smote)
print(np.round(wsumdf_similarity_pca))

[[-1.  0. -0. ... -0. -0. -0.]
 [-1.  0. -0. ... -0. -0. -0.]
 [-1.  0. -0. ... -0. -0. -0.]
 ...
 [-1. -0. -0. ... -0.  1.  0.]
 [-1. -0. -0. ... -0.  0.  0.]
 [-1.  0. -0. ... -0.  0.  0.]]


In [66]:
pca = PCA(n_components=10)
wmuldf_similarity_pca = pca.fit_transform(wmul_smote)
print(np.round(wmuldf_similarity_pca))

[[-1. -0.  0. ... -0. -0. -0.]
 [-1. -0.  0. ... -0. -0. -0.]
 [-1. -0.  0. ... -0. -0. -0.]
 ...
 [-1. -0.  0. ... -0. -0.  0.]
 [-1. -0. -0. ... -0. -0.  0.]
 [-1. -0. -0. ... -0. -0. -0.]]
